spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialize: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
decorator:
  datasource:
    p6spy:
      enable-logging: true
